# Generated by Django 4.0.3 on 2022-04-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '--0002_remove_cursos_horario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='FechaDeFin',
            new_name='fechaInicio',
        ),
        migrations.RenameField(
            model_name='entregables',
            old_name='FechaEntrega',
            new_name='fechaEntrega',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='FechaDeInicio',
        ),
        migrations.RemoveField(
            model_name='cursos',
            name='entregables',
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='curso',
            field=models.CharField(max_length=50),
        ),
    ]
